---
- hosts: all
  tasks:
    - name: Install various packages
      dnf:
        name:
          - cargo
          - direnv
          - exa
          - fish
          - git
          - python3-ipython
          - powerline
          - rust
          - tmux
          - tokei
          - python3-black
          - python3-isort
          - python37
        state: latest
    - name: Enable kakoune copr repository
      command: "dnf copr enable -y jkonecny/kakoune"
      args:
        creates: /etc/yum.repos.d/_copr_jkonecny-kakoune.repo
        warn: no
    - name: Install kakoune
      dnf:
        name: kakoune
        state: latest
