---
- hosts: all
  tasks:
    - name: Install various packages
      dnf:
        name:
          - cargo
          - direnv
          - etcd
          - exa
          - fd-find
          - fish
          - fzf
          - git
          - httpie
          - hub
          - lastpass-cli
          - libselinux-python
          - kubernetes
          - pipenv
          - python3-black
          - python3-ipython
          - python3-isort
          - python3-pygments
          - python37
          - powerline
          - powerline-fonts
          - ranger
          - ripgrep
          - rust
          - tmux
          - tmux-powerline
          - tokei
          - usbutils
          - ykclient
        state: latest
    - name: Enable kakoune copr repository
      command: "dnf copr enable -y jkonecny/kakoune"
      args:
        creates: /etc/yum.repos.d/_copr_jkonecny-kakoune.repo
        warn: no
    - name: Install kakoune
      dnf:
        name: kakoune
        state: latest
