---
- hosts: all
  tasks:
    - name: Install various packages
      dnf:
        name:
          - cargo
          - direnv
          - etcd
          - exa
          - fish
          - git
          - kubernetes
          - pipenv
          - python3-black
          - python3-ipython
          - python3-isort
          - python37
          - powerline
          - ranger
          - ripgrep
          - rust
          - tmux
          - tokei
        state: latest
    - name: Enable kakoune copr repository
      command: "dnf copr enable -y jkonecny/kakoune"
      args:
        creates: /etc/yum.repos.d/_copr_jkonecny-kakoune.repo
        warn: no
    - name: Install kakoune
      dnf:
        name: kakoune
        state: latest
